server:
  port: 9999
wx:
  mp:
    app-id: wxd4270c7f24a6f345
    secret: 83269d80153ce65c47b5453b39da68d9
    token: ssa
    config-storage:
      http-client-type: httpclient
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ppzdb?serverTimezone=PRC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 连接获取等待超时时间
    maxWait: 60000
    # 多久检测空闲连接，单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 连接在池中的最小生成时间
    minEvictableIdleTimeMills: 30000
    # 验证连接的sql
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 开启PSCache,并且指定每个连接缓存大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控拦截器
    filters: stat,wall,slf4j
    # 可以打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count==countSql
  page-size-zero: true
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true
dbName: ppzdb
